### PR TITLE
show default branch when building with params. show master if no default...

### PR DESCRIPTION
**Pull request by antweiss**
... is chosen
currently it always shows 'master'

### CODE REVIEW

**Comment by mklinke** [comment]
Can anyone tell when this fix will be available for regular installation as an update in Jenkins? Thanks in advance!

**Comment by antweiss** [comment]
It think @Eernie should have the merge permissions to this repository.

**Comment by mklinke** [comment]
@Eernie Thank you for merging this fix and sorry to bother you with another question here, but do you have any information on when there will be a new version of the plugin available for the update mechanism in Jenkins? Thanks.

**Comment by antweiss** [comment]
Thanks @Eernie !

**Comment by Eernie** [comment]
@mklinke i'll try to release it tonight, but I have to dust off my mac machine first. So I hope I'll get it released tonight!

**Comment by mklinke** [comment]
@Eernie Thanks, then I am patiently looking forward to the release :)

**Pull request merged**
